### PR TITLE
README: git lfs instructions

### LINKED ISSUE #3: Additional requirements and issues with apps/workbench
This seems to be the only repo that requires `git-lfs` which we could easily add to the docs it is needed if we want to keep it.

Unfortunately, I also received the following error when attempting to init this one:

```
Smudge error: Error downloading docs/live-balance-snapshots.mov (7f2d89059a5438c5936397d8916e4c71407a853a7acad2734b9745fc3460db61): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

What are your thoughts on how to proceed?

### PR DESCRIPTION
**Pull request by szTheory**

### CODE REVIEW

**Comment by joeybaer** [comment]
@szTheory What do you think of making this the default instead of optionally if you hit this error?

IMO I think we don't need any lfs file for the purpose of this repo and I would hate to utilize a repositories bandwidth if its not needed.

**Comment by szTheory** [comment]
Yeah that sounds good

**Comment by joeybaer** [comment]
> Yeah that sounds good

Awesome, I will keep an eye out for the update. Since we are making it the default vs in response to the error we could probably do a quick explanation why that env var is set kind of like how you had for other commands.

nice work 👍

**Comment by szTheory** [comment]
Are you able to edit this PR to add those changes yourself? I added you as a contributor but I'm not sure how to let you edit this PR from the Github UI

**Comment by szTheory** [comment]
Or you can open up a new PR with whatever changes in the README you want

**Comment by joeybaer** [comment]
@szTheory sure thing, lmk what you think.

**Comment by szTheory** [comment]
Perfect, thanks!

**Pull request merged**
